import { Student, Teacher, EventItem, HomeworkItem, TeacherPost } from './types';

// All 24 BBS Classes: Primary 1 to 6, Secondary 1 to 4, Junior College 1 to 2 (Sections A & B)
export const CLASSES = [
  // Primary (P1 - P6)
  'P1-A', 'P1-B',
  'P2-A', 'P2-B',
  'P3-A', 'P3-B',
  'P4-A', 'P4-B',
  'P5-A', 'P5-B',
  'P6-A', 'P6-B',
  // Secondary (S1 - S4)
  'S1-A', 'S1-B',
  'S2-A', 'S2-B',
  'S3-A', 'S3-B',
  'S4-A', 'S4-B',
  // Junior College (JC1 - JC2)
  'JC1-A', 'JC1-B',
  'JC2-A', 'JC2-B',
];

export const CLASS_DIVISIONS = [
  {
    division: 'Primary Division (P1 - P6)',
    code: 'primary',
    classes: ['P1-A', 'P1-B', 'P2-A', 'P2-B', 'P3-A', 'P3-B', 'P4-A', 'P4-B', 'P5-A', 'P5-B', 'P6-A', 'P6-B']
  },
  {
    division: 'Secondary Division (S1 - S4)',
    code: 'secondary',
    classes: ['S1-A', 'S1-B', 'S2-A', 'S2-B', 'S3-A', 'S3-B', 'S4-A', 'S4-B']
  },
  {
    division: 'Junior College (JC1 - JC2)',
    code: 'jc',
    classes: ['JC1-A', 'JC1-B', 'JC2-A', 'JC2-B']
  }
];

export const INITIAL_STUDENTS: Student[] = [
  // JC1-A (Senior Student Nicholas Tan & Classmates)
  {
    id: 's-101',
    name: 'Nicholas Tan',
    classId: 'JC1-A',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCBs0lMiiUNA8Xyb29FU_89TYEXd_Kijqh3mgpnGFsaWluEaAkRBugGs_0uwQiYL82lRYA9InyqbHZieKBbFqoloOYqucrGZ3tKNrMmuGsZIdq41olHGpoGMkZJhHNqYqa3X9TGAf8aswUVlg8SNAB_AWkpV0Kx5xM7OK_CUw-GnhfuusbpqExunH_lu57KYzaebjGxHaWAXRwWwFkP61qjSwTx2map5ePYAxXW2Tz8GTDaAEXDEY5c',
    email: 'stu17k1.nicholas@binabangsaschool.com',
    rollNumber: 'JC1A-14',
  },
  {
    id: 's-102',
    name: 'Chloe Lim',
    classId: 'JC1-A',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'chloe.lim@binabangsaschool.com',
    rollNumber: 'JC1A-05',
  },
  {
    id: 's-103',
    name: 'Marcus Wijaya',
    classId: 'JC1-A',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    email: 'marcus.w@binabangsaschool.com',
    rollNumber: 'JC1A-12',
  },
  {
    id: 's-107',
    name: 'Alex Tan',
    classId: 'JC1-A',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    email: 'alex.tan@binabangsaschool.com',
    rollNumber: 'JC1A-01',
  },
  {
    id: 's-108',
    name: 'Sarah Lim',
    classId: 'JC1-A',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    email: 'sarah.lim@binabangsaschool.com',
    rollNumber: 'JC1A-18',
  },
  {
    id: 's-109',
    name: 'Daniel Wong',
    classId: 'JC1-A',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    email: 'daniel.wong@binabangsaschool.com',
    rollNumber: 'JC1A-07',
  },
  {
    id: 's-110',
    name: 'Emily Lee',
    classId: 'JC1-A',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    email: 'emily.lee@binabangsaschool.com',
    rollNumber: 'JC1A-09',
  },

  // JC1-B
  {
    id: 's-104',
    name: 'Sophia Chen',
    classId: 'JC1-B',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    email: 'sophia.chen@binabangsaschool.com',
    rollNumber: 'JC1B-08',
  },
  {
    id: 's-111',
    name: 'Lucas Tanoto',
    classId: 'JC1-B',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    email: 'lucas.tanoto@binabangsaschool.com',
    rollNumber: 'JC1B-15',
  },

  // JC2-A & JC2-B
  {
    id: 's-106',
    name: 'Valerie Santoso',
    classId: 'JC2-A',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'valerie.s@binabangsaschool.com',
    rollNumber: 'JC2A-19',
  },
  {
    id: 's-113',
    name: 'Kevin Jonathan',
    classId: 'JC2-B',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    email: 'kevin.j@binabangsaschool.com',
    rollNumber: 'JC2B-04',
  },

  // Secondary S4-A & S4-B
  {
    id: 's-114',
    name: 'Jessica Halim',
    classId: 'S4-A',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    email: 'jessica.h@binabangsaschool.com',
    rollNumber: 'S4A-02',
  },
  {
    id: 's-115',
    name: 'Ryan Gunawan',
    classId: 'S4-B',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    email: 'ryan.g@binabangsaschool.com',
    rollNumber: 'S4B-11',
  },

  // Secondary S3-A & S3-B
  {
    id: 's-105',
    name: 'Ethan Hartono',
    classId: 'S3-A',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    email: 'ethan.h@binabangsaschool.com',
    rollNumber: 'S3A-03',
  },
  {
    id: 's-112',
    name: 'Hannah Kusuma',
    classId: 'S3-A',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    email: 'hannah.k@binabangsaschool.com',
    rollNumber: 'S3A-06',
  },
  {
    id: 's-116',
    name: 'Darren Setiawan',
    classId: 'S3-B',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    email: 'darren.s@binabangsaschool.com',
    rollNumber: 'S3B-09',
  },

  // Secondary S2-A & S2-B
  {
    id: 's-117',
    name: 'Rachel Pranata',
    classId: 'S2-A',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'rachel.p@binabangsaschool.com',
    rollNumber: 'S2A-14',
  },
  {
    id: 's-118',
    name: 'Brandon Li',
    classId: 'S2-B',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    email: 'brandon.li@binabangsaschool.com',
    rollNumber: 'S2B-07',
  },

  // Secondary S1-A & S1-B
  {
    id: 's-119',
    name: 'Grace Suryadi',
    classId: 'S1-A',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    email: 'grace.s@binabangsaschool.com',
    rollNumber: 'S1A-05',
  },
  {
    id: 's-120',
    name: 'Justin Chandra',
    classId: 'S1-B',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    email: 'justin.c@binabangsaschool.com',
    rollNumber: 'S1B-12',
  },

  // Primary P6-A & P6-B
  {
    id: 's-121',
    name: 'Megan Susanto',
    classId: 'P6-A',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    email: 'megan.s@binabangsaschool.com',
    rollNumber: 'P6A-08',
  },
  {
    id: 's-122',
    name: 'Nathaniel Hadi',
    classId: 'P6-B',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    email: 'nathaniel.h@binabangsaschool.com',
    rollNumber: 'P6B-10',
  },

  // Primary P5-A & P5-B
  {
    id: 's-123',
    name: 'Olivia Hartanto',
    classId: 'P5-A',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    email: 'olivia.h@binabangsaschool.com',
    rollNumber: 'P5A-03',
  },
  {
    id: 's-124',
    name: 'Samuel Wibowo',
    classId: 'P5-B',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    email: 'samuel.w@binabangsaschool.com',
    rollNumber: 'P5B-16',
  },

  // Primary P4-A & P4-B
  {
    id: 's-125',
    name: 'Alyssa Teo',
    classId: 'P4-A',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'alyssa.t@binabangsaschool.com',
    rollNumber: 'P4A-01',
  },
  {
    id: 's-126',
    name: 'Timothy Koh',
    classId: 'P4-B',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    email: 'timothy.k@binabangsaschool.com',
    rollNumber: 'P4B-14',
  },

  // Primary P3-A & P3-B
  {
    id: 's-127',
    name: 'Kayla Siregar',
    classId: 'P3-A',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    email: 'kayla.s@binabangsaschool.com',
    rollNumber: 'P3A-05',
  },
  {
    id: 's-128',
    name: 'Joshua Salim',
    classId: 'P3-B',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    email: 'joshua.s@binabangsaschool.com',
    rollNumber: 'P3B-11',
  },

  // Primary P2-A & P2-B
  {
    id: 's-129',
    name: 'Vanessa Lukito',
    classId: 'P2-A',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    email: 'vanessa.l@binabangsaschool.com',
    rollNumber: 'P2A-04',
  },
  {
    id: 's-130',
    name: 'Matthew Tjahja',
    classId: 'P2-B',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    email: 'matthew.t@binabangsaschool.com',
    rollNumber: 'P2B-09',
  },

  // Primary P1-A & P1-B
  {
    id: 's-131',
    name: 'Audrey Pangestu',
    classId: 'P1-A',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    email: 'audrey.p@binabangsaschool.com',
    rollNumber: 'P1A-02',
  },
  {
    id: 's-132',
    name: 'Benjamin Yosua',
    classId: 'P1-B',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    email: 'benjamin.y@binabangsaschool.com',
    rollNumber: 'P1B-06',
  },
];

export const TEACHERS: Teacher[] = [
  {
    id: 't-1',
    name: 'Dr. Rebecca Sterling',
    role: 'Head of Sciences & Academic Counselor',
    email: 'r.sterling@binabangsaschool.com',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 't-2',
    name: 'Mr. David Morales',
    role: 'Senior Physics & Robotics Teacher',
    email: 'd.morales@binabangsaschool.com',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 't-3',
    name: 'Ms. Clara Thorne',
    role: 'History Department Chair & Guidance Counselor',
    email: 'c.thorne@binabangsaschool.com',
    avatarUrl: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 't-4',
    name: 'Mrs. Emily Watson',
    role: 'Mathematics Specialist & Class 11-A Advisor',
    email: 'e.watson@binabangsaschool.com',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'ev-1',
    title: 'Science Fair & Robotics',
    date: '2026-08-27',
    startTime: '08:30 AM',
    endTime: '02:00 PM',
    details: 'Annual STEM exhibition showcasing student research experiments, interactive robotics displays, and chemistry demonstrations in the Main Auditorium.',
    counselors: ['Dr. Rebecca Sterling', 'Mr. David Morales'],
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80',
    targetAudience: 'ALL',
    category: 'academic',
    location: 'Main Auditorium & Science Wing',
    color: '#1a2b4b',
  },
  {
    id: 'ev-2',
    title: 'Physics Lab Practical',
    date: '2026-08-28',
    startTime: '10:15 AM',
    endTime: '12:00 PM',
    details: 'Hands-on practical session on electromagnetism and wave interference. All students must bring safety goggles and their laboratory notebooks.',
    counselors: ['Mr. David Morales'],
    imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&auto=format&fit=crop&q=80',
    targetAudience: 'CLASS',
    targetClass: 'JC1-A',
    category: 'academic',
    location: 'Physics Lab 3B',
    color: '#006a62',
  },
  {
    id: 'ev-3',
    title: 'History Essay Draft',
    date: '2026-08-31',
    startTime: '05:00 PM',
    endTime: '05:00 PM',
    details: 'Submission deadline for the 2,000-word historiographical essay draft analyzing the economic impacts of the Industrial Revolution in Southeast Asia.',
    counselors: ['Ms. Clara Thorne'],
    imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80',
    targetAudience: 'CLASS',
    targetClass: 'JC1-A',
    category: 'deadline',
    location: 'Online Portal',
    color: '#854d0e',
  },
  {
    id: 'ev-4',
    title: 'Math Competition',
    date: '2026-09-04',
    startTime: '09:00 AM',
    endTime: '12:30 PM',
    details: 'Regional Interschool Mathematics Invitational. Specific invitation event for selected BBS Olympiad team representatives: Alex Tan, Sarah Lim, Daniel Wong, and Nicholas Tan.',
    counselors: ['Mrs. Emily Watson', 'Dr. Rebecca Sterling'],
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80',
    targetAudience: 'GROUP_STUDENTS',
    targetClass: 'JC1-A',
    targetStudentIds: ['s-107', 's-108', 's-109', 's-101'],
    category: 'academic',
    location: 'Room 204 (Math Annex)',
    color: '#4338ca',
  },
  {
    id: 'ev-5',
    title: 'Inter-School Sports Gala',
    date: '2026-09-12',
    startTime: '08:00 AM',
    endTime: '04:30 PM',
    details: 'Annual sports festival featuring track and field events, basketball finals, and badminton championships. Parents and supporters are welcome.',
    counselors: ['Coach Alexander Tan', 'Ms. Clara Thorne'],
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&auto=format&fit=crop&q=80',
    targetAudience: 'ALL',
    category: 'sports',
    location: 'Main Stadium & Sports Complex',
    color: '#047857',
  },
  {
    id: 'ev-6',
    title: 'College Admissions Workshop',
    date: '2026-09-18',
    startTime: '01:00 PM',
    endTime: '03:30 PM',
    details: 'Essential seminar for Junior College students on crafting compelling personal statements, navigating Common App, and securing academic letters of recommendation.',
    counselors: ['Dr. Rebecca Sterling', 'Ms. Clara Thorne'],
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    targetAudience: 'CLASS',
    targetClass: 'JC1-A',
    category: 'workshop',
    location: 'College Guidance Center',
    color: '#7c2d12',
  },
];

export const INITIAL_HOMEWORK: HomeworkItem[] = [
  {
    id: 'hw-1',
    title: 'Physics Lab Report',
    subject: 'Physics',
    dueDate: '2026-08-28',
    dueTime: '11:59 PM',
    description: 'Complete calculation tables for harmonic oscillation, uncertainty analysis, and write the 300-word conclusion.',
    completed: false,
    submissionStatus: 'pending_approval',
    proofImageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&auto=format&fit=crop&q=80',
    submittedAt: 'Aug 26, 2026 • 08:45 PM',
    submittedByStudentId: 's-101',
    submittedByStudentName: 'Nicholas Tan',
    submittedByStudentClass: 'JC1-A',
    studentNotes: 'Attached handwritten oscillation measurements table and error bound analysis from Lab 3B.',
    targetAudience: 'CLASS',
    targetClass: 'JC1-A',
    assignedBy: 'Mr. David Morales',
    priority: 'high',
    submissions: {
      's-101': {
        studentId: 's-101',
        studentName: 'Nicholas Tan',
        studentClass: 'JC1-A',
        submissionStatus: 'pending_approval',
        completed: false,
        proofImageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&auto=format&fit=crop&q=80',
        submittedAt: 'Aug 26, 2026 • 08:45 PM',
        studentNotes: 'Attached handwritten oscillation measurements table and error bound analysis from Lab 3B.',
      },
    },
  },
  {
    id: 'hw-2',
    title: 'History Essay Draft',
    subject: 'World History',
    dueDate: '2026-08-31',
    dueTime: '05:00 PM',
    description: 'Submit preliminary bibliography with at least 5 primary sources and thesis outline for peer review.',
    completed: false,
    submissionStatus: 'not_submitted',
    targetAudience: 'CLASS',
    targetClass: 'JC1-A',
    assignedBy: 'Ms. Clara Thorne',
    priority: 'high',
    submissions: {},
  },
  {
    id: 'hw-3',
    title: 'Calculus Problem Set 4.2',
    subject: 'Mathematics',
    dueDate: '2026-08-29',
    dueTime: '08:00 AM',
    description: 'Solve exercises #14 to #32 on integration by parts and trigonometric substitutions.',
    completed: true,
    submissionStatus: 'approved',
    proofImageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80',
    submittedAt: 'Aug 26, 2026 • 07:15 PM',
    submittedByStudentId: 's-101',
    submittedByStudentName: 'Nicholas Tan',
    submittedByStudentClass: 'JC1-A',
    studentNotes: 'Checked all steps using substitution formulas on pages 14-16.',
    reviewedByTeacherName: 'Mrs. Emily Watson',
    reviewedAt: 'Aug 26, 2026 • 09:20 PM',
    teacherFeedback: 'Outstanding work Nicholas! All trigonometric derivations are correct.',
    targetAudience: 'CLASS',
    targetClass: 'JC1-A',
    assignedBy: 'Mrs. Emily Watson',
    priority: 'medium',
    submissions: {
      's-101': {
        studentId: 's-101',
        studentName: 'Nicholas Tan',
        studentClass: 'JC1-A',
        submissionStatus: 'approved',
        completed: true,
        proofImageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80',
        submittedAt: 'Aug 26, 2026 • 07:15 PM',
        studentNotes: 'Checked all steps using substitution formulas on pages 14-16.',
        reviewedByTeacherName: 'Mrs. Emily Watson',
        reviewedAt: 'Aug 26, 2026 • 09:20 PM',
        teacherFeedback: 'Outstanding work Nicholas! All trigonometric derivations are correct.',
      },
    },
  },
  {
    id: 'hw-4',
    title: 'Literature Reading: Macbeth Act III',
    subject: 'English Lit',
    dueDate: '2026-09-02',
    dueTime: '09:00 AM',
    description: 'Annotate key soliloquies in scenes 1-4 and prepare two discussion questions for the Socratic seminar.',
    completed: false,
    submissionStatus: 'not_submitted',
    targetAudience: 'ALL',
    assignedBy: 'Ms. Clara Thorne',
    priority: 'medium',
    submissions: {},
  },
  {
    id: 'hw-5',
    title: 'Organic Chemistry Nomenclature',
    subject: 'Chemistry',
    dueDate: '2026-09-03',
    dueTime: '03:00 PM',
    description: 'Workbook pages 88-92 on functional groups, IUPAC naming conventions, and stereoisomers.',
    completed: true,
    submissionStatus: 'approved',
    proofImageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80',
    submittedAt: 'Aug 25, 2026 • 02:30 PM',
    submittedByStudentId: 's-101',
    submittedByStudentName: 'Nicholas Tan',
    submittedByStudentClass: 'JC1-A',
    reviewedByTeacherName: 'Dr. Rebecca Sterling',
    reviewedAt: 'Aug 25, 2026 • 04:10 PM',
    teacherFeedback: 'Verified. Great IUPAC nomenclature notation.',
    targetAudience: 'CLASS',
    targetClass: 'JC1-A',
    assignedBy: 'Dr. Rebecca Sterling',
    priority: 'medium',
    submissions: {
      's-101': {
        studentId: 's-101',
        studentName: 'Nicholas Tan',
        studentClass: 'JC1-A',
        submissionStatus: 'approved',
        completed: true,
        proofImageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80',
        submittedAt: 'Aug 25, 2026 • 02:30 PM',
        reviewedByTeacherName: 'Dr. Rebecca Sterling',
        reviewedAt: 'Aug 25, 2026 • 04:10 PM',
        teacherFeedback: 'Verified. Great IUPAC nomenclature notation.',
      },
    },
  },
  {
    id: 'hw-6',
    title: 'Personal Math Olympiad Worksheet #3',
    subject: 'Advanced Math',
    dueDate: '2026-08-30',
    dueTime: '04:00 PM',
    description: 'Combinatorics challenge problems assigned for upcoming tournament prep.',
    completed: false,
    submissionStatus: 'not_submitted',
    targetAudience: 'SINGLE_STUDENT',
    targetClass: 'JC1-A',
    targetStudentIds: ['s-101'],
    assignedBy: 'Mrs. Emily Watson',
    priority: 'high',
    submissions: {},
  },
  {
    id: 'hw-7',
    title: 'French Oral Recording: Mon Quotidien',
    subject: 'French',
    dueDate: '2026-09-05',
    dueTime: '11:59 PM',
    description: 'Record a 2-minute audio reflection in French detailing your daily routine and weekend aspirations.',
    completed: true,
    submissionStatus: 'approved',
    proofImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCuEWQqOv3l1tWdFP92TXdflfYx_mrC2fT2rL-iUwm52DHymyLxgCByNEKK5O4_kl8MRC8W9DR3VBy97u1cbvfzawjr-s4hPaMgxAoH5mcd6Yaeya6AckCOm9S5PIjwoJggzK8HgET9A2yYQxXzGmGUCF5lq7Mxf_fyzp6_7cJR8fXTp5EeIG3XAwBYTjf2WLssyu4vUBww219O_V3HOErmSSBbT9vDZNl6bmN4MsG-m2A1xUNIHA_U',
    submittedAt: 'Aug 26, 2026 • 06:10 PM',
    submittedByStudentId: 's-101',
    submittedByStudentName: 'Nicholas Tan',
    submittedByStudentClass: 'JC1-A',
    reviewedByTeacherName: 'Mme. Rousseau',
    reviewedAt: 'Aug 27, 2026 • 09:00 AM',
    teacherFeedback: 'Très bien! Clear pronunciation and good vocabulary usage.',
    targetAudience: 'CLASS',
    targetClass: 'JC1-A',
    assignedBy: 'Mme. Rousseau',
    priority: 'low',
    submissions: {
      's-101': {
        studentId: 's-101',
        studentName: 'Nicholas Tan',
        studentClass: 'JC1-A',
        submissionStatus: 'approved',
        completed: true,
        proofImageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCuEWQqOv3l1tWdFP92TXdflfYx_mrC2fT2rL-iUwm52DHymyLxgCByNEKK5O4_kl8MRC8W9DR3VBy97u1cbvfzawjr-s4hPaMgxAoH5mcd6Yaeya6AckCOm9S5PIjwoJggzK8HgET9A2yYQxXzGmGUCF5lq7Mxf_fyzp6_7cJR8fXTp5EeIG3XAwBYTjf2WLssyu4vUBww219O_V3HOErmSSBbT9vDZNl6bmN4MsG-m2A1xUNIHA_U',
        submittedAt: 'Aug 26, 2026 • 06:10 PM',
        reviewedByTeacherName: 'Mme. Rousseau',
        reviewedAt: 'Aug 27, 2026 • 09:00 AM',
        teacherFeedback: 'Très bien! Clear pronunciation and good vocabulary usage.',
      },
    },
  },
  {
    id: 'hw-8',
    title: 'Computer Science: Recursion Algorithms',
    subject: 'Computer Science',
    dueDate: '2026-09-08',
    dueTime: '11:59 PM',
    description: 'Implement binary search and tree traversal in TypeScript and write unit tests.',
    completed: true,
    submissionStatus: 'approved',
    proofImageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    submittedAt: 'Aug 25, 2026 • 09:30 PM',
    submittedByStudentId: 's-101',
    submittedByStudentName: 'Nicholas Tan',
    submittedByStudentClass: 'JC1-A',
    reviewedByTeacherName: 'Mr. David Morales',
    reviewedAt: 'Aug 26, 2026 • 08:30 AM',
    teacherFeedback: 'Clean recursion logic and robust test edge cases.',
    targetAudience: 'CLASS',
    targetClass: 'JC1-A',
    assignedBy: 'Mr. David Morales',
    priority: 'medium',
    submissions: {
      's-101': {
        studentId: 's-101',
        studentName: 'Nicholas Tan',
        studentClass: 'JC1-A',
        submissionStatus: 'approved',
        completed: true,
        proofImageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
        submittedAt: 'Aug 25, 2026 • 09:30 PM',
        reviewedByTeacherName: 'Mr. David Morales',
        reviewedAt: 'Aug 26, 2026 • 08:30 AM',
        teacherFeedback: 'Clean recursion logic and robust test edge cases.',
      },
    },
  },
];

export const INITIAL_POSTS: TeacherPost[] = [
  {
    id: 'post-1',
    teacherName: 'Dr. Rebecca Sterling',
    teacherRole: 'Head of Sciences & Academic Counselor',
    teacherAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    title: 'Science Fair & Exhibition 2026 Safety Briefing',
    date: 'Aug 27, 2026',
    category: 'announcement',
    priorityNotice: true,
    fullMessage: 'Dear students, as we prepare for the annual Science Fair today, please ensure that all chemical substances are safely stored and labeled according to lab safety protocols. Setup begins at 7:45 AM in the Main Auditorium. Best of luck with your final project demonstrations!',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80',
    targetClass: 'ALL',
    likesCount: 24,
    likedByCurrentUser: true,
  },
  {
    id: 'post-2',
    teacherName: 'Ms. Clara Thorne',
    teacherRole: 'Guidance Counselor & History Chair',
    teacherAvatar: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80',
    title: 'Important Reminder: History Draft Rubric Updates',
    date: 'Aug 26, 2026',
    category: 'reminder',
    fullMessage: 'Please review the updated historiographical rubric uploaded to the digital library. Make sure to cite at least three peer-reviewed secondary sources alongside your archival documents. Consultation hours are open every Tuesday and Thursday afternoon.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCuEWQqOv3l1tWdFP92TXdflfYx_mrC2fT2rL-iUwm52DHymyLxgCByNEKK5O4_kl8MRC8W9DR3VBy97u1cbvfzawjr-s4hPaMgxAoH5mcd6Yaeya6AckCOm9S5PIjwoJggzK8HgET9A2yYQxXzGmGUCF5lq7Mxf_fyzp6_7cJR8fXTp5EeIG3XAwBYTjf2WLssyu4vUBww219O_V3HOErmSSBbT9vDZNl6bmN4MsG-m2A1xUNIHA_U',
    targetClass: 'JC1-A',
    likesCount: 18,
    likedByCurrentUser: false,
  },
  {
    id: 'post-3',
    teacherName: 'Mrs. Emily Watson',
    teacherRole: 'Mathematics Specialist & Advisor',
    teacherAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    title: 'Math Olympiad Intensive Practice Session',
    date: 'Aug 25, 2026',
    category: 'deadline',
    fullMessage: 'A special notification for our selected Olympiad candidates: Please pick up your practice packets from Room 204 before Friday. We will cover number theory and geometric proofs during our clinic.',
    targetClass: 'JC1-A',
    targetStudentIds: ['s-101', 's-103'],
    likesCount: 9,
    likedByCurrentUser: true,
  },
];
